# Generated by Django 3.1.3 on 2025-02-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('study', 'Study'), ('entertainment', 'Entertainment')], default='work', max_length=50),
        ),
    ]
